//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSchool.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Absences
    {
        public int AbsenceID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public Nullable<System.DateTime> AbsenceDate { get; set; }
        public string Reason { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual Students Students { get; set; }
    }
}
