//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSchool.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analysis
    {
        public int AnalysisId { get; set; }
        public Nullable<int> IdResource { get; set; }
        public string CountResource { get; set; }
    
        public virtual ResourceType ResourceType { get; set; }
    }
}
