//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSchool.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedbackID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> InstructorID { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<System.DateTime> FeedbackDate { get; set; }
    
        public virtual Instructors Instructors { get; set; }
        public virtual Students Students { get; set; }
    }
}
