//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSchool.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grades
    {
        public int GradeID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> AttendancePercentage { get; set; }
        public Nullable<int> TheoreticalExamScore { get; set; }
        public Nullable<int> PracticalExamScore { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
