//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSchool.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceHistory
    {
        public int MaintenanceID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<System.DateTime> MaintenanceDate { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Vehicles Vehicles { get; set; }
    }
}
