//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSchool.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int NotificationID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
