//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSchool.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceUtilization
    {
        public int ResourceID { get; set; }
        public string ResourceType { get; set; }
        public string ResourceName { get; set; }
        public Nullable<int> NumberOfSessions { get; set; }
        public Nullable<int> TotalMinutesScheduled { get; set; }
    }
}
